<?php
	define('URL', __DIR__.'/'); //mere in cod PHP ... ar trebui ...
	define('URL2', '//localhost/Catalog_v2/'); //mere in cod HTML ...
	require 'config/autoloader.php';
		
	$application = new Bootsite();
