<?php
	//define('URL', __DIR__.'/../'); //Folosita in cod PHP ...
	//define('URL', '//localhost/Catalog_v2/'); //Folosita in cod PHP ...
	//define('URL', 'http://localhost/Catalog_v2/'); //Used in cod HTML ...
	